-- DB software used: MYSQL Workbench.
-- NAME: Meghana Putta Swamy
-- USC ID : 6565038173
-- NETID: mswamy
-- ASSUMPTION: P333 will never have C,W,C,W for example [all Cs will occur before all Ws]. Just printing PID in the output


CREATE TABLE PROJECT_STATUS(
PID VARCHAR(10) NOT NULL,
STEP INTEGER NOT NULL,
STAT VARCHAR(2) NOT NULL,
PRIMARY KEY (PID, STEP)
);

INSERT INTO PROJECT_STATUS VALUES ('P100',0,'C');
INSERT INTO PROJECT_STATUS VALUES ('P100',1,'W');
INSERT INTO PROJECT_STATUS VALUES ('P100',2,'W');
INSERT INTO PROJECT_STATUS VALUES ('P201',0,'C');
INSERT INTO PROJECT_STATUS VALUES ('P201',1,'C');
INSERT INTO PROJECT_STATUS VALUES ('P333',0,'W');
INSERT INTO PROJECT_STATUS VALUES ('P333',1,'W');
INSERT INTO PROJECT_STATUS VALUES ('P333',2,'W');
INSERT INTO PROJECT_STATUS VALUES ('P333',3,'W');


SELECT PID FROM PROJECT_STATUS 
WHERE (STEP=0 AND STAT='C') AND PID NOT IN ( SELECT PID FROM PROJECT_STATUS WHERE STEP=1 AND STAT='C');


