-- DB software used: MYSQL Workbench.
-- NAME: Meghana Putta Swamy
-- USC ID : 6565038173
-- NETID: mswamy
-- ASSUMPTION: every instructor charges different hourly rate, so i have added a cloumn corresponding to that value

CREATE TABLE INSTRUCTOR_BONUS( 
INSTRUCTOR_ID INTEGER NOT NULL,
INSTRUCTOR_NAME VARCHAR(30) NOT NULL,
CLASS_TAUGHT VARCHAR(10) NOT NULL,
STD_ENROLLED INTEGER NOT NULL,
HOURLY_RATE NUMERIC(10,3) NOT NULL,
PRIMARY KEY (INSTRUCTOR_ID, CLASS_TAUGHT)
);

INSERT INTO INSTRUCTOR_BONUS VALUES(111,'AMBER','PYTHON',20,20.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(112,'BOB','PYTHON',10,30.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(113,'CLAIRE','PYTHON',15,15.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(111,'AMBER','SCRATCH',15,20.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(112,'BOB','SCRATCH',10,30.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(114,'DEAN','PROCESSING',40,20.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(114,'DEAN','JAVASCRIPT',20,20.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(111,'AMBER','JAVASCRIPT',50,20.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(112,'BOB','JAVASCRIPT',20,30.00);
INSERT INTO INSTRUCTOR_BONUS VALUES(113,'CLAIRE','JAVASCRIPT',10,15.00);

SELECT MAX(BONUS) FROM (SELECT SUM(STD_ENROLLED*HOURLY_RATE*0.1) AS BONUS FROM INSTRUCTOR_BONUS
GROUP BY (INSTRUCTOR_NAME))AS BONUS_TABLE;