
-- DB software used: MYSQL Workbench.
-- NAME: Meghana Putta Swamy
-- USC ID : 6565038173
-- NETID: mswamy 

CREATE TABLE INSTRUCTOR_SUBJECT(
INSTRUCTOR VARCHAR(30) NOT NULL,
SUBJECT VARCHAR(30) NOT NULL,
PRIMARY KEY (INSTRUCTOR, SUBJECT)
);

INSERT INTO INSTRUCTOR_SUBJECT VALUES('Aleph','Scratch');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Aleph','Java');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Aleph','Processing');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Bit','Python');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Bit','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Bit','Java');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('CRC','Python');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('CRC','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Dat','Scratch');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Dat','Python');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Dat','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','Scratch');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','Processing');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','Python'); 

CREATE TABLE SUBJECTS(
    SUBJECT_JD Char(30),
    PRIMARY KEY(SUBJECT_JD));

INSERT INTO Subjects VALUES ('Javascript'); 
INSERT INTO Subjects VALUES ('Scratch'); 
INSERT INTO Subjects VALUES ('Python');


SELECT i1.INSTRUCTOR
FROM INSTRUCTOR_SUBJECT i1
WHERE i1.SUBJECT IN (SELECT SUBJECT_JD FROM SUBJECTS)
GROUP BY i1.INSTRUCTOR
HAVING COUNT(*) = (SELECT COUNT(*) FROM SUBJECTS) 

-- Note:
-- Created table SUBJECTS of the all the subjects which need in the job description
-- Then extract the INSTRUCTORS in the table INSTRUCTOR_SUBJECT who teaches all the subjects contained in the table SUBJECTS using count.

