-- DB software used: MYSQL Workbench.
-- NAME: Meghana Putta Swamy
-- USC ID : 6565038173
-- NETID: mswamy 

CREATE TABLE INSTRUCTOR_SUBJECT(
INSTRUCTOR VARCHAR(30) NOT NULL,
SUBJECT VARCHAR(30) NOT NULL,
PRIMARY KEY (INSTRUCTOR, SUBJECT)
);

INSERT INTO INSTRUCTOR_SUBJECT VALUES('Aleph','Scratch');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Aleph','Java');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Aleph','Processing');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Bit','Python');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Bit','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Bit','Java');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('CRC','Python');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('CRC','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Dat','Scratch');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Dat','Python');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Dat','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','Scratch');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','Processing');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','JavaScript');
INSERT INTO INSTRUCTOR_SUBJECT VALUES('Emscr','Python');

-- just to check what all subjects are available in the INSTRUCTOR_SUBJECT table before deciding on what is not needed. 
SELECT DISTINCT(SUBJECT) AS DISTINCT_SUB FROM INSTRUCTOR_SUBJECT; 

SELECT INSTRUCTOR FROM INSTRUCTOR_SUBJECT
WHERE SUBJECT IN(SELECT DISTINCT(SUBJECT) AS UNIQUE_SUBJECT FROM INSTRUCTOR_SUBJECT WHERE SUBJECT != 'PROCESSING' && SUBJECT != 'JAVA')
GROUP BY INSTRUCTOR 
HAVING COUNT(DISTINCT SUBJECT)=(SELECT COUNT(UNIQUE_SUBJECT) 
FROM (SELECT DISTINCT(SUBJECT) AS UNIQUE_SUBJECT 
		FROM INSTRUCTOR_SUBJECT WHERE SUBJECT != 'PROCESSING' && SUBJECT != 'JAVA' )AS UNI);


-- There are two parts to this query: 
-- 1. SELECT INSTRUCTOR FROM INSTRUCTOR_SUBJECT
-- 		WHERE SUBJECT IN(SELECT DISTINCT(SUBJECT) AS UNIQUE_SUBJECT FROM INSTRUCTOR_SUBJECT WHERE SUBJECT != 'PROCESSING' && SUBJECT != 'JAVA')
-- select all instructors that teaches subjects other than PROCESSING and JAVA(here I am checking for subjects which are not needed 
-- because rest all subjects are in job description) 
-- I am using subquery where I find the list of DISTINCT subjects from INSTRUCTOR_SUBJECT table other than PROCESSING and JAVA
-- 2. GROUP BY INSTRUCTOR 
-- 		FROM (SELECT DISTINCT(SUBJECT) AS UNIQUE_SUBJECT 
-- 		FROM INSTRUCTOR_SUBJECT WHERE SUBJECT != 'PROCESSING' && SUBJECT != 'JAVA' )AS UNI);
-- after grouping by instructor counting the number of subjects that instructor has 
-- and comparing it with the count of distinct subjects that is needed. If they are equal then the instructors names are listed

