-- DB software used: MYSQL Workbench.
-- NAME: Meghana Putta Swamy
-- USC ID : 6565038173
-- NETID: mswamy

CREATE TABLE CLASS_ENROLLMENT(
SID INTEGER NOT NULL,
CLASSNAME VARCHAR(20) NOT NULL,
GRADE VARCHAR(5) NOT NULL,
PRIMARY KEY (SID, CLASSNAME) 
);

INSERT INTO CLASS_ENROLLMENT VALUES(123, 'PROCESSING', 'A'); 
INSERT INTO CLASS_ENROLLMENT VALUES(123, 'PYTHON', 'B');
INSERT INTO CLASS_ENROLLMENT VALUES(123, 'SCRATCH', 'B');
INSERT INTO CLASS_ENROLLMENT VALUES(662, 'JAVA', 'B');
INSERT INTO CLASS_ENROLLMENT VALUES(662, 'PYTHON', 'A');
INSERT INTO CLASS_ENROLLMENT VALUES(662, 'JAVASCRIPT', 'A');
INSERT INTO CLASS_ENROLLMENT VALUES(662, 'SCRATCH', 'B');
INSERT INTO CLASS_ENROLLMENT VALUES(345, 'JAVASCRIPT', 'B');
INSERT INTO CLASS_ENROLLMENT VALUES(345, 'SCRATCH', 'A');
INSERT INTO CLASS_ENROLLMENT VALUES(345, 'PYTHON', 'A');
INSERT INTO CLASS_ENROLLMENT VALUES(555, 'PYTHON', 'B');
INSERT INTO CLASS_ENROLLMENT VALUES(555, 'JAVASCRIPT', 'B');
INSERT INTO CLASS_ENROLLMENT VALUES(213, 'JAVASCRIPT', 'A');

SELECT CLASSNAME, COUNT(*) AS TOTAL	
FROM CLASS_ENROLLMENT
GROUP BY CLASSNAME
ORDER BY TOTAL DESC; 
