USE CSCI_585;
CREATE TABLE PRODUCT (
P_CODE		VARCHAR(10)		NOT NULL,
P_INDATE	DATE			NOT NULL,
P_QOH		SMALLINT		NOT NULL,		
P_PRICE		NUMERIC(8,2)	NOT NULL,
V_CODE		INTEGER,
PRIMARY KEY (P_CODE),
FOREIGN KEY (V_CODE) REFERENCES VENDOR(V_CODE) ON UPDATE CASCADE);

